### PR TITLE
updated strings (german), added function to display playtime correctly

### PR DESCRIPTION
**Pull request by PliPla**
- added function to display video playtime correctly
-- instead of displaying 134 mins it now displays 2h 14m
-- see: https://emby.media/community/index.php?/topic/62584-show-2-hours-14-minutes-instead-of-134-mins/

- added a note how to maybe improve look and feel of how episodes are being displayed in a card
--  currently it's "S1E2". Maybe it would be better readable with leading zeros and a middle dot.

### CODE REVIEW

**Comment by PliPla** [comment]
Additional note for the season/episode thing:
the leading zeros should only be there so the Season and Episode are always minimum 2 numbers.
So instead of S1E2 it would be S01E02.
Season 20 Episode 123 would be S20S123 nevertheless.

**Comment by LukePulverenti** [comment]
I will look at the code, but please submit the updated strings on onesky, our translations site. thanks.

**Comment by LukePulverenti** [comment]
And also please sign our contributor license agreement so that we can use this code. Thanks.

**Comment by PliPla** [comment]
My english is -really- bad. What, in short, do I accept there?
If you want to use my code... just take it. I would even send it to you per email.

**Comment by LukePulverenti** [comment]
I'm going to rewrite it anyway, thanks.

**Pull request closed without merging**
